### ISSUE TITLE
Problema al ejecutar script

### ISSUE THREAD

**Issue by darkane188** [BrahianVT/reconocimiento-de-patrones-implementando-la-red-neuronal-Perceptron-multiple-en-Python#2]
![image](https://user-images.githubusercontent.com/10376033/61920077-e147c400-af1d-11e9-8e68-ecfea45ca1d3.png)

**Comment by BrahianVT** [comment]
Hola darkane188 parece que no se genero el archivo de matriz_final.npy checa si existe y sea en la misma carpeta o en otro que se alla generado
